train: /content/taco-dataset/train/images
val: /content/taco-dataset/val/images

# number of classes
nc: 7

# class names
names: ['metals_and_plastic', 'other', 'non_recyclable', 'glass', 'paper', 'bio', 'unknown']
